---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: default-ingress
  template:
    metadata:
      labels:
        app.kubernetes.io/name: default-ingress
    spec:
      containers:
        - name: default-ingress
          image: nginx
          resources:
            requests:
              cpu: "10m"
              memory: "25Mi"
            limits:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
---

