---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{ if eq .Values.cloud "aws" }}
    alb.ingress.kubernetes.io/group.name: default-alb
    alb.ingress.kubernetes.io/scheme: internet-facing # provision external IP
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    {{ end }}
  name: default-ingress
spec:
  {{ if eq .Values.cloud "aws" }}
  ingressClassName: alb
  {{ end }}
  {{ if eq .Values.cloud "azure" }}
  ingressClassName: azure-application-gateway
  {{ end }}
  rules:
    - host: default-ingress.local
      http:
        paths:
          - backend:
              service:
                name: default-ingress
                port:
                  number: 80
            path: /
            pathType: Exact
---

