---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: default-alb
    alb.ingress.kubernetes.io/scheme: internet-facing # provision external IP
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  name: default-ingress
spec:
  ingressClassName: alb
  rules:
    - host: default-ingress.local
      http:
        paths:
          - backend:
              service:
                name: default-ingress
                port:
                  number: 80
            path: /
            pathType: Exact
---

